/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sathish' at '1/16/17 4:30 PM' with Gradle 2.14.1
 *
 * @author Sathish, @date 1/16/17 4:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
